from subsearch.utils import io_app

DEVICE_INFO = io_app.get_system_info()
VIDEO_FILE = io_app.get_video_file_data()
APP_PATHS = io_app.get_app_paths()
FILE_PATHS = io_app.get_file_paths()
FILE_EXTENSIONS = io_app.get_file_extensions()
SUBTITLE_PROVIDERS = io_app.get_subtitle_providers()
DEFAULT_CONFIG = io_app.get_default_app_config()
REGISTRY_PATHS = io_app.get_windows_registry_paths()
COMPUTER_NAME = io_app.get_computer_name()
VERSION = io_app.get_app_version()
CONFIG_CONFLICT_MAP = io_app.get_config_conflict_map()
REGISTRY_CONFLICT_MAP = io_app.get_registry_conflict_map()
REGISTRY_OPTIONS_MAP = io_app.get_registry_options_map()
GUID = io_app.get_guid()
