from subsearch import bootstrap

DEVICE_INFO = bootstrap.get_system_info()
VIDEO_FILE = bootstrap.get_video_file_data()
APP_PATHS = bootstrap.get_app_paths()
FILE_PATHS = bootstrap.get_file_paths()
FILE_EXTENSIONS = bootstrap.get_file_extensions()
SUBTITLE_PROVIDERS = bootstrap.get_subtitle_providers()
DEFAULT_CONFIG = bootstrap.get_default_app_config()
REGISTRY_PATHS = bootstrap.get_windows_registry_paths()
COMPUTER_NAME = bootstrap.get_computer_name()
VERSION = bootstrap.get_app_version()
CONFIG_CONFLICT_MAP = bootstrap.get_config_conflict_map()
DISABLE_STATE_MAP = bootstrap.get_disable_state_map()
REGISTRY_OPTIONS_MAP = bootstrap.get_registry_options_map()
GUID = bootstrap.get_guid()
