[tox]
minversion = 4.0
env_list =
    py314
labels =
     test = py314

[gh-actions]
python =
    3.14: py314

[testenv]
description = run the test suite with pytest
passenv = PYTHONPATH
deps = -e .[tests]
isolated_build = true

[testenv:py314]
description = Python 3.14
commands = pytest --cov