from subsearch.runtime.keys import LogEvent

EVENTS: dict[LogEvent, str] = {
    LogEvent.BANNER: "{title}",
    LogEvent.TASK_COMPLETED: "Tasks completed",
    LogEvent.VIDEO_FILE_SELECTED: "Selected {filename}",
    LogEvent.SEARCH_TERM_SET: "Search term set: {term}",
    LogEvent.SUBTITLE_MATCH: "{subtitle_name}",
    LogEvent.SUBTITLE_REJECTED: "{subtitle_name}",
    LogEvent.PROVIDER_SKIPS: "{provider:<14}skipped {total} ({breakdown})",
    LogEvent.REMOVE: r"Removing {kind}: ...\{src}",
    LogEvent.RENAME: "Renamed to {dst_name}",
    LogEvent.MOVE: r"Moving {kind}: ...\{src} -> ...\{dst}",
    LogEvent.EXTRACT: "Extracting {src_name}",
    LogEvent.POST_PROCESSING_STARTED: "Unpacking subtitles to {destination}",
    LogEvent.POST_PROCESSING_COMPLETED: "Moved {moved} subtitles to {destination}",
    LogEvent.POST_PROCESSING_NO_FILES: "No subtitles unpacked or moved (moved {moved})",
    LogEvent.POST_PROCESSING_FAILED: "Could not unpack subtitles: {reason}",
    LogEvent.CONFIG_CHANGED: "Config change: {change}",
    LogEvent.CONFIG_COMMITTED: "Settings saved",
    LogEvent.CONFIG_REVERTED: "Discarded unsaved settings",
    LogEvent.CONFIG_SCHEMA_MISMATCH: "Config schema mismatch, repairing",
    LogEvent.CONFIG_KEY_REMOVED: "Removing obsolete config key {key}",
    LogEvent.CONFIG_KEY_ADDED: "Adding missing config key {key}",
    LogEvent.CONFIG_RESET: "Settings reset to defaults",
    LogEvent.CONFIG_RESTORED: "Restored settings from backup",
    LogEvent.CONFIG_RESTORE_ATTEMPT: "Config missing or unreadable, attempting restore from backup",
    LogEvent.CONFIG_UNREADABLE_AFTER_RESTORE: "Config is unreadable after restore, resetting to defaults",
    LogEvent.CONFIG_INTEGRITY_PASSED: "Config integrity check passed",
    LogEvent.CONFIG_REPAIR_SUCCEEDED: "Config repair succeeded",
    LogEvent.CONFIG_REPAIR_FAILED: "Config repair failed, resetting to defaults",
    LogEvent.CONFIG_WRITE_FAILED: "Failed to write config to {filename}: {reason}",
    LogEvent.CONFIG_READ: "Read json file from {filename}",
    LogEvent.CONFIG_WROTE: "Wrote config to {filename}",
    LogEvent.HTTP_REQUEST_FAILED: "Request failed for {url}: {reason}",
    LogEvent.HTTP_BAD_STATUS: "Request to {url} returned status {status_code}",
    LogEvent.REGISTRY_ATTEMPTING: "Attempting registry {action}: {target}",
    LogEvent.REGISTRY_KEY_DELETING: "Deleting registry key: {key}",
    LogEvent.REGISTRY_CONTEXT_MENU_REMOVING: "Removing Subsearch context menu from registry",
    LogEvent.REGISTRY_KEY_MISSING: "Registry key missing, could not write {sub_key}\\{value_name}",
    LogEvent.REGISTRY_RECONCILE_SKIPPED: "Skipping registry reconcile: MSI installer owns the context menu keys",
    LogEvent.REGISTRY_MATCHES_ABSENT: "Registry matches config: context menu absent",
    LogEvent.REGISTRY_MATCHES_CURRENT: "Registry matches config: context menu up to date",
    LogEvent.REGISTRY_VALUE_UPDATED: "Registry updated: {name}",
    LogEvent.REGISTRY_LONG_PATHS_DISABLED: "Win32 long paths are not enabled, long file names may fail",
    LogEvent.REGISTRY_LONG_PATHS_KEY_MISSING: "Win32 long paths registry key not found, assuming disabled",
    LogEvent.REGISTRY_LONG_PATHS_CHECK_FAILED: "Failed to check long path status: {reason}",
    LogEvent.IMDB_CONNECTING: "Fuzzy matching {term!r}",
    LogEvent.IMDB_SUGGESTIONS_FAILED: "IMDb connection failed while fetching suggestions for {term!r}",
    LogEvent.IMDB_NO_SUGGESTIONS: "IMDb returned no suggestions for {term!r}",
    LogEvent.IMDB_SUGGESTIONS: "IMDb returned {count} title suggestion(s) for {term!r}",
    LogEvent.IMDB_LOOKUP_FAILED: "IMDb connection failed while looking up {title!r}",
    LogEvent.IMDB_NO_RESULTS: "IMDb returned no results for {title!r}",
    LogEvent.IMDB_MATCHED: "IMDb matched {title!r} -> {imdb_id}",
    LogEvent.IMDB_NO_MATCH: "IMDb lookup found no matching entry for {title!r} ({year}, tvseries={tvseries})",
    LogEvent.PROVIDER_SEARCHING: "{provider}: searching",
    LogEvent.PROVIDER_SEARCH_RESULT: "{provider}: found {found} ({accepted} accepted, {rejected} rejected)",
    LogEvent.PROVIDER_MIRROR_TRIED: "{provider}: trying mirror {url}",
    LogEvent.PROVIDER_NO_MIRROR_RESPONDED: "{provider}: no mirror responded",
    LogEvent.PROVIDER_STRUCTURE_INVALID: "{provider}: mirror responded but page structure was invalid",
    LogEvent.PROVIDER_UNRECOGNIZED_RESPONSE: "{provider} response was unrecognized: {reason}",
    LogEvent.PROVIDER_SKIPPED_NO_API_KEY: (
        "{provider} skipped: no API key configured. Add your Subsource API key in settings."
    ),
    LogEvent.PROVIDER_SKIP_REASON: "{reason}",
    LogEvent.PROVIDER_OPENSUBTITLES_DOWN: "opensubtitles is down: {reason}",
    LogEvent.PROVIDER_SUBSOURCE_STATUS: "{url} status_code: {status_code} {reason}",
    LogEvent.PROVIDER_FILENAME_SANITIZED: "Filename sanitized: {original!r} -> {sanitized!r}",
    LogEvent.DIAGNOSTICS_HEALTHY: "{provider}: healthy, resetting failed_attempts to 0",
    LogEvent.DIAGNOSTICS_UNHEALTHY: (
        "{provider}: unhealthy ({status}, found {found}), failed_attempts {previous} -> {updated}"
    ),
    LogEvent.DIAGNOSTICS_DUE: "Providers due for diagnostic (threshold={threshold}): {providers}",
    LogEvent.DIAGNOSTICS_RUNNING: "Running diagnostics for: {providers}",
    LogEvent.DIAGNOSTICS_PROBING: "Probing {provider}",
    LogEvent.DIAGNOSTICS_SKIPPED_NO_API_KEY: "{provider}: skipped, missing API key",
    LogEvent.DIAGNOSTICS_RESULT: "{provider}: {status} ({diagnostic_status}, found {found})",
    LogEvent.FS_CREATING: "Creating {path}",
    LogEvent.FS_HASHING: "Calculating hash of video file",
    LogEvent.FS_INVALID_FILE_SIZE: "Invalid file size, {size} bytes",
    LogEvent.FS_DESTINATION_MISSING: "Destination directory {path} does not exist, moving to {fallback} instead",
    LogEvent.FS_ARCHIVE_OVERSIZE: "Archive uncompressed size {size} exceeds limit, skipping",
    LogEvent.FS_ARCHIVE_UNSAFE_PATH: "Skipping unsafe path in archive: {filename}",
    LogEvent.FS_ARCHIVE_UNREADABLE: "Skipping unreadable archive {name}\n{traceback}",
    LogEvent.DOWNLOAD_SUBTITLE: "Downloading {subtitle_name}",
    LogEvent.DOWNLOAD_NOT_ZIP: (
        "{provider}: {subtitle_name} is not a zip (status {status_code}, cloudflare {cloudflare}) "
        "from {url}, skipping download"
    ),
    LogEvent.DOWNLOAD_STARTED: "Download started for {filename}",
    LogEvent.DOWNLOAD_PROGRESS: "Downloading {percentage}%",
    LogEvent.DOWNLOAD_COMPLETED: "Download complete",
    LogEvent.UPDATE_FAILED: "Update download failed",
    LogEvent.UPDATE_DOWNLOADED: "MSI file downloaded to: {destination}",
    LogEvent.UPDATE_CHANGELOG_FAILED: "Failed to fetch changelog: {reason}",
    LogEvent.PIPELINE_DIAGNOSTICS_FLAGGED: "Provider diagnostics flagged: {message}",
    LogEvent.PIPELINE_PROVIDER_CHANGED: "{provider} may have changed, unrecognized response",
    LogEvent.PIPELINE_SUMMARY_SUCCEEDED: "{summary}",
    LogEvent.PIPELINE_SUMMARY_FAILED: "{summary}",
    LogEvent.PIPELINE_FINISHED: "Finished in {seconds} seconds",
    LogEvent.BOOT_ARGV: "sys.argv: {argv}",
    LogEvent.BOOT_VIDEO_FILE: "Video file {presence}: {path}",
    LogEvent.BOOT_VERIFYING: "Verifying files and paths",
    LogEvent.BOOT_TRAY_INIT: "Initializing system tray icon",
    LogEvent.BOOT_GUI_WARMUP: "GUI warmup triggered",
    LogEvent.BOOT_GUI_OPENED: "GUI opened",
    LogEvent.BOOT_GUI_CLOSED: "GUI closed",
    LogEvent.BOOT_LONG_PATHS_DISABLED: (
        "Win32 long paths disabled; paths >260 chars may fail. Set LongPathsEnabled=1 and reboot."
    ),
    LogEvent.BOOT_LONG_PATHS_HELP: "https://github.com/vagabondHustler/Win32LongPaths",
    LogEvent.THREAD_SUBMITTING: "Submitting {count} thread(s): {names}",
    LogEvent.THREAD_FAILED: "Thread {name} raised an exception\n{traceback}",
    LogEvent.THREAD_COMPLETED: "Thread {name} completed",
    LogEvent.THREAD_JOINED: "All threads joined: {names}",
    LogEvent.FLOW_FILENAME_HAS_SPACES: "{filename} contains spaces, result may vary",
    LogEvent.TRAY_ADDED: "Subsearch was added to the system tray",
    LogEvent.TRAY_REMOVED: "Subsearch was removed from the system tray",
    LogEvent.TASK_FAILED: "{reason}",
    LogEvent.GUARD_STEP_SKIPPED: "skipped {qualified_name}",
    LogEvent.GUARD_STEP_CALLED: "called {qualified_name}",
    LogEvent.GUARD_SINGLE_INSTANCE: "Single-instance enforcement: {single_instance}",
    LogEvent.GUARD_SINGLE_INSTANCE_DISABLED: "Single-instance disabled, skipping mutex",
    LogEvent.GUARD_MUTEX_ACQUIRED: "Mutex acquired: {guid}",
    LogEvent.GUARD_MUTEX_RELEASED: "Mutex released: {guid}",
    LogEvent.RUN_CONDITIONS_EVALUATED: "run_conditions [{step}]: {detail} -> {decision}",
    LogEvent.TRACKER_TRACKING: "Tracking {path}",
    LogEvent.TRACKER_RELEASED: "Released {path}",
    LogEvent.TRACKER_DISCARDING_STALE: "Discarding stale tracked path {path}",
    LogEvent.TRACKER_MANIFEST_UNREADABLE: "Unreadable file manifest at {path}, starting fresh",
    LogEvent.TRACKER_REFUSING_UNTRACKED: "Refusing to delete untracked path {path}",
    LogEvent.TRACKER_RECLAIMING: "Reclaiming leftover temp path {path}",
    LogEvent.SCORE_EXACT_TOKEN_MATCH: "Fuzzy match: exact token match for {from_provider!r}",
    LogEvent.SCORE_BREAKDOWN: "Fuzzy match: {score}% for {from_provider!r} (base {base}, mismatch ×{mismatch})",
}

# A plain-language progress feed the user can act on: phase markers, the found
# subtitle list, downloads, and the handful of saved/restored/failed lines.
# Everything else is forensic detail that belongs only in the log file.
# Promoting a new event to the console is a deliberate edit to this set.
CONSOLE_EVENTS: frozenset[LogEvent] = frozenset(
    {
        LogEvent.BANNER,
        LogEvent.VIDEO_FILE_SELECTED,
        LogEvent.SUBTITLE_MATCH,
        LogEvent.SUBTITLE_REJECTED,
        LogEvent.RENAME,
        LogEvent.EXTRACT,
        LogEvent.CONFIG_COMMITTED,
        LogEvent.CONFIG_REVERTED,
        LogEvent.CONFIG_RESET,
        LogEvent.CONFIG_RESTORED,
        LogEvent.IMDB_CONNECTING,
        LogEvent.DOWNLOAD_SUBTITLE,
        LogEvent.UPDATE_FAILED,
        LogEvent.BOOT_LONG_PATHS_DISABLED,
        LogEvent.BOOT_LONG_PATHS_HELP,
    }
)

FILESYSTEM_EVENTS: frozenset[LogEvent] = frozenset({LogEvent.REMOVE, LogEvent.RENAME, LogEvent.MOVE, LogEvent.EXTRACT})
