from enum import StrEnum


class LogEvent(StrEnum):
    BANNER = "banner"
    TASK_COMPLETED = "task_completed"
    VIDEO_FILE_SELECTED = "video_file_selected"
    SEARCH_TERM_SET = "search_term_set"
    SUBTITLE_MATCH = "subtitle_match"
    SUBTITLE_REJECTED = "subtitle_rejected"
    PROVIDER_SKIPS = "provider_skips"
    REMOVE = "remove"
    RENAME = "rename"
    MOVE = "move"
    EXTRACT = "extract"
    POST_PROCESSING_STARTED = "post_processing_started"
    POST_PROCESSING_COMPLETED = "post_processing_completed"
    POST_PROCESSING_NO_FILES = "post_processing_no_files"
    POST_PROCESSING_FAILED = "post_processing_failed"

    CONFIG_CHANGED = "config.changed"
    CONFIG_COMMITTED = "config.committed"
    CONFIG_REVERTED = "config.reverted"
    CONFIG_SCHEMA_MISMATCH = "config.schema_mismatch"
    CONFIG_KEY_REMOVED = "config.key_removed"
    CONFIG_KEY_ADDED = "config.key_added"
    CONFIG_RESET = "config.reset"
    CONFIG_RESTORED = "config.restored"
    CONFIG_RESTORE_ATTEMPT = "config.restore_attempt"
    CONFIG_UNREADABLE_AFTER_RESTORE = "config.unreadable_after_restore"
    CONFIG_INTEGRITY_PASSED = "config.integrity_passed"
    CONFIG_REPAIR_SUCCEEDED = "config.repair_succeeded"
    CONFIG_REPAIR_FAILED = "config.repair_failed"
    CONFIG_WRITE_FAILED = "config.write_failed"
    CONFIG_READ = "config.read"
    CONFIG_WROTE = "config.wrote"

    HTTP_REQUEST_FAILED = "http.request_failed"
    HTTP_BAD_STATUS = "http.bad_status"

    REGISTRY_ATTEMPTING = "registry.attempting"
    REGISTRY_KEY_DELETING = "registry.key_deleting"
    REGISTRY_CONTEXT_MENU_REMOVING = "registry.context_menu_removing"
    REGISTRY_KEY_MISSING = "registry.key_missing"
    REGISTRY_RECONCILE_SKIPPED = "registry.reconcile_skipped"
    REGISTRY_MATCHES_ABSENT = "registry.matches_absent"
    REGISTRY_MATCHES_CURRENT = "registry.matches_current"
    REGISTRY_VALUE_UPDATED = "registry.value_updated"
    REGISTRY_LONG_PATHS_DISABLED = "registry.long_paths_disabled"
    REGISTRY_LONG_PATHS_KEY_MISSING = "registry.long_paths_key_missing"
    REGISTRY_LONG_PATHS_CHECK_FAILED = "registry.long_paths_check_failed"

    IMDB_CONNECTING = "imdb.connecting"
    IMDB_SUGGESTIONS_FAILED = "imdb.suggestions_failed"
    IMDB_NO_SUGGESTIONS = "imdb.no_suggestions"
    IMDB_SUGGESTIONS = "imdb.suggestions"
    IMDB_LOOKUP_FAILED = "imdb.lookup_failed"
    IMDB_NO_RESULTS = "imdb.no_results"
    IMDB_MATCHED = "imdb.matched"
    IMDB_NO_MATCH = "imdb.no_match"

    PROVIDER_SEARCHING = "provider.searching"
    PROVIDER_SEARCH_RESULT = "provider.search_result"
    PROVIDER_MIRROR_TRIED = "provider.mirror_tried"
    PROVIDER_NO_MIRROR_RESPONDED = "provider.no_mirror_responded"
    PROVIDER_STRUCTURE_INVALID = "provider.structure_invalid"
    PROVIDER_UNRECOGNIZED_RESPONSE = "provider.unrecognized_response"
    PROVIDER_SKIPPED_NO_API_KEY = "provider.skipped_no_api_key"
    PROVIDER_SKIP_REASON = "provider.skip_reason"
    PROVIDER_OPENSUBTITLES_DOWN = "provider.opensubtitles_down"
    PROVIDER_SUBSOURCE_STATUS = "provider.subsource_status"
    PROVIDER_FILENAME_SANITIZED = "provider.filename_sanitized"

    DIAGNOSTICS_HEALTHY = "diagnostics.healthy"
    DIAGNOSTICS_UNHEALTHY = "diagnostics.unhealthy"
    DIAGNOSTICS_DUE = "diagnostics.due"
    DIAGNOSTICS_RUNNING = "diagnostics.running"
    DIAGNOSTICS_PROBING = "diagnostics.probing"
    DIAGNOSTICS_SKIPPED_NO_API_KEY = "diagnostics.skipped_no_api_key"
    DIAGNOSTICS_RESULT = "diagnostics.result"

    FS_CREATING = "fs.creating"
    FS_HASHING = "fs.hashing"
    FS_INVALID_FILE_SIZE = "fs.invalid_file_size"
    FS_DESTINATION_MISSING = "fs.destination_missing"
    FS_ARCHIVE_OVERSIZE = "fs.archive_oversize"
    FS_ARCHIVE_UNSAFE_PATH = "fs.archive_unsafe_path"
    FS_ARCHIVE_UNREADABLE = "fs.archive_unreadable"

    DOWNLOAD_SUBTITLE = "download.subtitle"
    DOWNLOAD_NOT_ZIP = "download.not_zip"
    DOWNLOAD_STARTED = "download.started"
    DOWNLOAD_PROGRESS = "download.progress"
    DOWNLOAD_COMPLETED = "download.completed"

    UPDATE_FAILED = "update.failed"
    UPDATE_DOWNLOADED = "update.downloaded"
    UPDATE_CHANGELOG_FAILED = "update.changelog_failed"

    PIPELINE_DIAGNOSTICS_FLAGGED = "pipeline.diagnostics_flagged"
    PIPELINE_PROVIDER_CHANGED = "pipeline.provider_changed"
    PIPELINE_SUMMARY_SUCCEEDED = "pipeline.summary_succeeded"
    PIPELINE_SUMMARY_FAILED = "pipeline.summary_failed"
    PIPELINE_FINISHED = "pipeline.finished"

    BOOT_ARGV = "boot.argv"
    BOOT_VIDEO_FILE = "boot.video_file"
    BOOT_VERIFYING = "boot.verifying"
    BOOT_TRAY_INIT = "boot.tray_init"
    BOOT_GUI_WARMUP = "boot.gui_warmup"
    BOOT_GUI_OPENED = "boot.gui_opened"
    BOOT_GUI_CLOSED = "boot.gui_closed"
    BOOT_LONG_PATHS_DISABLED = "boot.long_paths_disabled"
    BOOT_LONG_PATHS_HELP = "boot.long_paths_help"

    THREAD_SUBMITTING = "thread.submitting"
    THREAD_FAILED = "thread.failed"
    THREAD_COMPLETED = "thread.completed"
    THREAD_JOINED = "thread.joined"

    FLOW_FILENAME_HAS_SPACES = "flow.filename_has_spaces"

    TRAY_ADDED = "tray.added"
    TRAY_REMOVED = "tray.removed"

    TASK_FAILED = "task.failed"

    GUARD_STEP_SKIPPED = "guard.step_skipped"
    GUARD_STEP_CALLED = "guard.step_called"
    GUARD_SINGLE_INSTANCE = "guard.single_instance"
    GUARD_SINGLE_INSTANCE_DISABLED = "guard.single_instance_disabled"
    GUARD_MUTEX_ACQUIRED = "guard.mutex_acquired"
    GUARD_MUTEX_RELEASED = "guard.mutex_released"

    RUN_CONDITIONS_EVALUATED = "run_conditions.evaluated"

    TRACKER_TRACKING = "tracker.tracking"
    TRACKER_RELEASED = "tracker.released"
    TRACKER_DISCARDING_STALE = "tracker.discarding_stale"
    TRACKER_MANIFEST_UNREADABLE = "tracker.manifest_unreadable"
    TRACKER_REFUSING_UNTRACKED = "tracker.refusing_untracked"
    TRACKER_RECLAIMING = "tracker.reclaiming"

    SCORE_EXACT_TOKEN_MATCH = "score.exact_token_match"
    SCORE_BREAKDOWN = "score.breakdown"
