name: release

on:
  push:
    tags:
      - "v*"
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Release with File
        uses: softprops/action-gh-release@v1
        with:
          files: dist/SubSearch.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
