# Name of the workflow
name: Release

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"

# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release"
    runs-on: "windows-latest"
    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false

  build:
      runs-on: windows-latest
      steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          path: dist
          filename: 'SubSearch.exe.zip'
          exclusions: '*.git* /*node_modules/* .editorconfig'

  upload:
      - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "SubSearch.exe.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
