import dearpygui.dearpygui as dpg


# catppuccin mocha
# refrence https://github.com/catppuccin/catppuccin
COLOR_NAME: dict[str, list[int]] = {
    "rosewater": [245, 224, 220, 255],
    "flamingo": [242, 205, 205, 255],
    "pink": [245, 194, 231, 255],
    "mauve": [203, 166, 247, 255],
    "red": [243, 139, 168, 255],
    "maroon": [235, 160, 172, 255],
    "peach": [250, 179, 135, 255],
    "yellow": [249, 226, 175, 255],
    "green": [166, 227, 161, 255],
    "teal": [148, 226, 213, 255],
    "sky": [137, 220, 235, 255],
    "sapphire": [116, 199, 236, 255],
    "blue": [137, 180, 250, 255],
    "lavender": [180, 190, 254, 255],
    "text": [205, 214, 244, 255],
    "subtext1": [186, 194, 222, 255],
    "subtext0": [166, 173, 200, 255],
    "overlay2": [147, 153, 178, 255],
    "overlay1": [127, 132, 156, 255],
    "overlay0": [108, 112, 134, 255],
    "surface2": [88, 91, 112, 255],
    "surface1": [69, 71, 90, 255],
    "surface0": [49, 50, 68, 255],
    "base": [30, 30, 46, 255],
    "mantle": [24, 24, 37, 255],
    "crust": [17, 17, 27, 255],
    "transparent": [0, 0, 0, 0],
}


COLOR_MAP: dict[int, list[int]] = {
    dpg.mvThemeCol_Text: COLOR_NAME["text"],
    dpg.mvThemeCol_TextDisabled: COLOR_NAME["subtext1"],
    dpg.mvThemeCol_WindowBg: COLOR_NAME["crust"],
    dpg.mvThemeCol_ChildBg: COLOR_NAME["base"],
    dpg.mvThemeCol_PopupBg: COLOR_NAME["mantle"],
    dpg.mvThemeCol_Border: COLOR_NAME["surface1"],
    dpg.mvThemeCol_BorderShadow: COLOR_NAME["transparent"],
    dpg.mvThemeCol_FrameBg: COLOR_NAME["surface1"],
    dpg.mvThemeCol_FrameBgHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_FrameBgActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_TitleBg: COLOR_NAME["surface1"],
    dpg.mvThemeCol_TitleBgActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_TitleBgCollapsed: COLOR_NAME["surface0"],
    dpg.mvThemeCol_MenuBarBg: COLOR_NAME["surface0"],
    dpg.mvThemeCol_ScrollbarBg: COLOR_NAME["surface0"],
    dpg.mvThemeCol_ScrollbarGrab: COLOR_NAME["surface1"],
    dpg.mvThemeCol_ScrollbarGrabHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_ScrollbarGrabActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_CheckMark: COLOR_NAME["green"],
    dpg.mvThemeCol_SliderGrab: COLOR_NAME["pink"],
    dpg.mvThemeCol_SliderGrabActive: COLOR_NAME["pink"],
    dpg.mvThemeCol_Button: COLOR_NAME["mantle"],
    dpg.mvThemeCol_ButtonHovered: COLOR_NAME["base"],
    dpg.mvThemeCol_ButtonActive: COLOR_NAME["surface0"],
    dpg.mvThemeCol_Header: COLOR_NAME["surface1"],
    dpg.mvThemeCol_HeaderHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_HeaderActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_Separator: COLOR_NAME["surface1"],
    dpg.mvThemeCol_SeparatorHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_SeparatorActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_ResizeGrip: COLOR_NAME["surface1"],
    dpg.mvThemeCol_ResizeGripHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_ResizeGripActive: COLOR_NAME["surface2"],
    dpg.mvThemeCol_Tab: COLOR_NAME["surface1"],
    dpg.mvThemeCol_TabHovered: COLOR_NAME["surface2"],
    dpg.mvThemeCol_DockingPreview: COLOR_NAME["pink"],
    dpg.mvThemeCol_DockingEmptyBg: COLOR_NAME["mantle"],
    dpg.mvThemeCol_PlotLines: COLOR_NAME["pink"],
    dpg.mvThemeCol_PlotLinesHovered: COLOR_NAME["red"],
    dpg.mvThemeCol_PlotHistogram: COLOR_NAME["pink"],
    dpg.mvThemeCol_PlotHistogramHovered: COLOR_NAME["red"],
    dpg.mvThemeCol_TableHeaderBg: COLOR_NAME["surface0"],
    dpg.mvThemeCol_TableBorderStrong: COLOR_NAME["surface1"],
    dpg.mvThemeCol_TableBorderLight: COLOR_NAME["surface0"],
    dpg.mvThemeCol_TableRowBg: COLOR_NAME["surface0"],
    dpg.mvThemeCol_TableRowBgAlt: COLOR_NAME["surface1"],
    dpg.mvThemeCol_TextSelectedBg: COLOR_NAME["pink"],
    dpg.mvThemeCol_DragDropTarget: COLOR_NAME["yellow"],
    dpg.mvThemeCol_NavHighlight: COLOR_NAME["pink"],
    dpg.mvThemeCol_NavWindowingHighlight: COLOR_NAME["pink"],
    dpg.mvThemeCol_NavWindowingDimBg: COLOR_NAME["mantle"],
    dpg.mvThemeCol_ModalWindowDimBg: COLOR_NAME["mantle"],
}


STYLE_MAP: dict[int, list[int]] = {
    dpg.mvStyleVar_WindowPadding: [0, 0],
    dpg.mvStyleVar_FramePadding: [2, 2],
    dpg.mvStyleVar_CellPadding: [8, 2],
    dpg.mvStyleVar_ItemSpacing: [1, 1],
    dpg.mvStyleVar_ItemInnerSpacing: [2, 4],
    dpg.mvStyleVar_IndentSpacing: [21],
    dpg.mvStyleVar_ScrollbarSize: [2],
    dpg.mvStyleVar_GrabMinSize: [12],
    dpg.mvStyleVar_WindowBorderSize: [0],
    dpg.mvStyleVar_ChildBorderSize: [0],
    dpg.mvStyleVar_PopupBorderSize: [0],
    dpg.mvStyleVar_FrameBorderSize: [0],
    dpg.mvStyleVar_TabBorderSize: [0],
    dpg.mvStyleVar_TabBarBorderSize: [0],
    dpg.mvStyleVar_WindowRounding: [0],
    dpg.mvStyleVar_ChildRounding: [6],
    dpg.mvStyleVar_FrameRounding: [2],
    dpg.mvStyleVar_PopupRounding: [0],
    dpg.mvStyleVar_ScrollbarRounding: [0],
    dpg.mvStyleVar_GrabRounding: [8],
    dpg.mvStyleVar_TabRounding: [4],
}
